### ISSUE TITLE
IndexError: index 2743 is out of bounds for axis 0 with size 100 ？？how to deal with this ？

### ISSUE THREAD

**Issue by dw1360585641** [tonyhuang2022/UPL#15]
Building transform_test
+ resize the smaller edge to 224
+ 224x224 center crop
+ to torch tensor of range [0, 1]
+ normalization (mean=[0.48145466, 0.4578275, 0.40821073], std=[0.26862954, 0.26130258, 0.27577711])
Building transform_train
+ random resized crop (size=(224, 224), scale=(0.08, 1.0))
+ random flip
+ to torch tensor of range [0, 1]
+ normalization (mean=[0.48145466, 0.4578275, 0.40821073], std=[0.26862954, 0.26130258, 0.27577711])
Loading CLIP (backbone: RN50)
Building custom CLIP
Initializing a generic context
Initial context: "X X X X X X X X X X X X X X X X"
Number of context words (tokens): 16
Turning off gradients in both the image and the text encoder
Loading evaluator: UPLClassification
Traceback (most recent call last):
  File "upl_train.py", line 225, in <module>
    main(args)
  File "upl_train.py", line 143, in main
    model_names=cfg.MODEL.PSEUDO_LABEL_MODELS)
  File "/data/kb/wdw/upl/trainers/upltrainer.py", line 578, in load_from_exist_file
    predict_label_dict, predict_conf_dict = select_top_k_similarity_per_class(logits, sstrain_img_paths, K=self.cfg.DATASET.NUM_SHOTS, is_softmax=False)
  File "/data/kb/wdw/upl/trainers/utils.py", line 99, in select_top_k_similarity_per_class
    img_paths = img_paths[output_m_max_id]
IndexError: index 2743 is out of bounds for axis 0 with size 100
！！！！！！！when I followed your instructions to train CUDA_VISIBLEDEVICES=0 bash up_train.sh sscaltech101 rn50_ ep50 end 16 16 False True rn50_random_init, and encountered this problem. How can I solve it？

**Comment by dw1360585641** [comment]
@tonyhuang2022
